version: '3.8'

services:
  api-python:
    build:
      context: ./server/python
    ports:
      - "8000:8000"
    environment:
      - GEMINI_TOKEN_API_KEY=${GEMINI_TOKEN_API_KEY}
    restart: unless-stopped
    depends_on:
      - api-js
    networks:
      - gemini-network

  api-js:
    build:
      context: ./server/nextjs
    ports:
      - "4100:4100"
    environment:
      - GEMINI_TOKEN_API_KEY=${GEMINI_TOKEN_API_KEY}
    restart: unless-stopped
    networks:
      - gemini-network

networks:
  gemini-network:
    driver: bridge
